/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BUS;

import DAO.AccountDAO;
import DAO.InformationaccountDAO;
import POJO.Account;
import POJO.Informationaccount;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nthan
 */
public class AccountInfor extends javax.swing.JPanel {

    /**
     * Creates new form AccountInfor
     */
    public AccountInfor() {
        initComponents();
        setInforOfAccounr();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_address = new javax.swing.JTextField();
        text_fullname = new javax.swing.JTextField();
        cb_sex = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("User name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 53, 0, 0);
        add(jLabel1, gridBagConstraints);

        text_username.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 249;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 39, 0, 10);
        add(text_username, gridBagConstraints);

        jLabel2.setText("Full name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 53, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel4.setText("Sex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 53, 0, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 53, 0, 0);
        add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 249;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 39, 0, 10);
        add(text_address, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 249;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 39, 0, 10);
        add(text_fullname, gridBagConstraints);

        cb_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "null" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 39, 0, 0);
        add(cb_sex, gridBagConstraints);

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 74, 11, 0);
        add(btn_update, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String userName = text_username.getText();
        String fullName = text_fullname.getText();
        String Address = text_address.getText();
        int sex = -1;
        if(cb_sex.getSelectedItem().toString().equals("Male") == true)
            sex = 0;
        else if(cb_sex.getSelectedItem().toString().equals("Female") == true)
            sex = 1;
        else{}
        Informationaccount test = InformationaccountDAO.getInformationAccountByUserName(userName);
        if(test != null){
            System.out.println("ko null");
            Informationaccount infor = new
            Informationaccount(String.valueOf(test.getId()),
                AccountDAO.getInformationAccount(userName), 
                 fullName, sex, Address);
            if(InformationaccountDAO.updateInformationAccount(infor) == true){
                 JOptionPane.showMessageDialog(new JFrame(), "Successful",
                    "Notification",JOptionPane.PLAIN_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(new JFrame(), "False",
                    "Notification",JOptionPane.PLAIN_MESSAGE);
            }
        }
        else{
            System.out.println("co null");
            Informationaccount infor = new
            Informationaccount(String.valueOf(InformationaccountDAO.getIDMax(userName) + 1),
                AccountDAO.getInformationAccount(userName), 
                 fullName, sex, Address);
            if(InformationaccountDAO.addInformationAccount(infor) == true){
                JOptionPane.showMessageDialog(new JFrame(), "Successful",
                    "Notification",JOptionPane.PLAIN_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(new JFrame(), "False",
                    "Notification",JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    public void setInforOfAccounr(){
        text_username.setText(Login.userNamelocal);
        Informationaccount inforAccount = 
                InformationaccountDAO.getInformationAccountByUserName(Login.userNamelocal);
        if(inforAccount == null){
            text_fullname.setText("null");
            text_address.setText("null");
            cb_sex.setSelectedItem("null");
            return;
        }
        text_fullname.setText(inforAccount.getName());
        text_address.setText(inforAccount.getAddress());
        if(inforAccount.getSex() == 0){
            cb_sex.setSelectedItem("Male");
        }
        else if(inforAccount.getSex() == 1){
            cb_sex.setSelectedItem("Female");
        }
        else
            cb_sex.setSelectedItem("null");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_sex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField text_address;
    private javax.swing.JTextField text_fullname;
    private javax.swing.JTextField text_username;
    // End of variables declaration//GEN-END:variables
}
