/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BUS;
import DAO.AccountDAO;
import DAO.StudentDAO;
import DAO.SubjectDAO;
import POJO.Account;
import POJO.Studentofsubject;
import POJO.StudentofsubjectId;
import POJO.Subject;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
/**
 *
 * @author nthan
 */
public class ImportCSV extends javax.swing.JPanel {

    /**
     * Creates new form ImportCSV
     */
    public String linkFile = "";
    public int indexIDSubject = -1;
    public int indexUserName = -1;
    public ImportCSV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text_link = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_IDSubjet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_Username = new javax.swing.JTextField();
        btn_OK = new javax.swing.JButton();
        btn_import = new javax.swing.JButton();

        jLabel1.setText("LINK FILE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TEMPLATE");

        jLabel3.setText("ID subject");

        jLabel4.setText("User name");

        btn_OK.setText("OK");
        btn_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OKActionPerformed(evt);
            }
        });

        btn_import.setText("Import CSV");
        btn_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(text_link, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_IDSubjet)
                                    .addComponent(text_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btn_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(btn_import)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_OK)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_IDSubjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btn_import)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OKActionPerformed
        linkFile = text_link.getText();
        BufferedReader br = null;
        String line = "";
        String cvsSplitBy = ",";
        try{
             br = new BufferedReader(new FileReader(linkFile));
             boolean checkTemplate = false;
             if(br == null)
                 System.out.println("fail");
            while ((line = br.readLine()) != null) {
                String iDsub = "";
                String userName = "";
                
                String[] country = line.split(cvsSplitBy);
                if(country[0].equals("ID subject") == true && checkTemplate == false){
                    indexIDSubject = 0;
                    indexUserName = 1;
                    checkTemplate = true;

                }
                if(country[0].equals("ID subject") != true && checkTemplate == false)
                {
                    indexIDSubject = 1;
                    indexUserName = 0;
                }
                iDsub = country[indexIDSubject];
                userName = country[indexUserName];
                Account account = AccountDAO.getInformationAccount(userName);
                POJO.Subject subject = SubjectDAO.getInformationSubjectByID(iDsub);
                if(account != null || subject != null){
                    StudentofsubjectId sbId =  new StudentofsubjectId(iDsub, userName);
                    Studentofsubject studentOfSubject = new Studentofsubject(sbId, account,subject,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
                    StudentDAO.addStudentOfSubject(studentOfSubject);
                        
                }
            }
        }
        catch(IOException ex){
            ex.printStackTrace();
        }
        finally{
            try{
            if( br!=null)
                br.close();
            }catch(Exception ex){}
        }

    }//GEN-LAST:event_btn_OKActionPerformed

    public void checkTemplate(){
        linkFile = text_link.getText();
        BufferedReader br = null;
        String line = "";
        String cvsSplitBy = ",";
        try{
             br = new BufferedReader(new FileReader(linkFile));
             boolean checkTemplate = false;
             if(br == null)
                 System.out.println("fail");
            while ((line = br.readLine()) != null) {
                String iDsub = "";
                String userName = "";
                
                String[] country = line.split(cvsSplitBy);
                if(country[0].equals("ID subject") == true && checkTemplate == false){
                    indexIDSubject = 0;
                    indexUserName = 1;
                    checkTemplate = true;

                }
                if(country[0].equals("ID subject") != true && checkTemplate == false)
                {
                    indexIDSubject = 1;
                    indexUserName = 0;
                }
            }
        }
        catch(IOException ex){
            ex.printStackTrace();
        }
        finally{
            try{
            if( br!=null)
                br.close();
            }catch(Exception ex){}
        }
    }
    private void btn_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importActionPerformed
       checkTemplate();
        FileWriter pw = null;
        if(text_IDSubjet.getText().equals("") == true|| 
                text_Username.getText().equals("") == true)
            return;
        try{
        pw = new FileWriter(linkFile, true);
        if(indexIDSubject == 0){
            pw.append(text_IDSubjet.getText());
            pw.append(",");
            pw.append(text_Username.getText());
            pw.append("\n");
        }
        else
        {
            pw.append(text_Username.getText());  
            pw.append(",");
            pw.append(text_IDSubjet.getText());
            pw.append("\n");
        }
       }
       catch(IOException f){
           
       }
        try{
         pw.flush();
         pw.close();
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_btn_importActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_OK;
    private javax.swing.JButton btn_import;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField text_IDSubjet;
    private javax.swing.JTextField text_Username;
    private javax.swing.JTextField text_link;
    // End of variables declaration//GEN-END:variables
}
