package POJO;
// Generated Apr 10, 2017 8:42:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String userName;
     private String passWord;
     private int type;
     private Set<Informationaccount> informationaccounts = new HashSet<Informationaccount>(0);
     private Set<Subject> subjects = new HashSet<Subject>(0);
     private Set<Studentofsubject> studentofsubjects = new HashSet<Studentofsubject>(0);

    public Account() {
    }

	
    public Account(String userName, String passWord, int type) {
        this.userName = userName;
        this.passWord = passWord;
        this.type = type;
    }
    public Account(String userName, String passWord, int type, Set<Informationaccount> informationaccounts, Set<Subject> subjects, Set<Studentofsubject> studentofsubjects) {
       this.userName = userName;
       this.passWord = passWord;
       this.type = type;
       this.informationaccounts = informationaccounts;
       this.subjects = subjects;
       this.studentofsubjects = studentofsubjects;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Set<Informationaccount> getInformationaccounts() {
        return this.informationaccounts;
    }
    
    public void setInformationaccounts(Set<Informationaccount> informationaccounts) {
        this.informationaccounts = informationaccounts;
    }
    public Set<Subject> getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set<Subject> subjects) {
        this.subjects = subjects;
    }
    public Set<Studentofsubject> getStudentofsubjects() {
        return this.studentofsubjects;
    }
    
    public void setStudentofsubjects(Set<Studentofsubject> studentofsubjects) {
        this.studentofsubjects = studentofsubjects;
    }




}


