package POJO;
// Generated Apr 10, 2017 8:42:19 PM by Hibernate Tools 4.3.1



/**
 * Informationaccount generated by hbm2java
 */
public class Informationaccount  implements java.io.Serializable {


     private String id;
     private Account account;
     private String name;
     private Integer sex;
     private String address;

    public Informationaccount() {
    }

	
    public Informationaccount(String id, String name) {
        this.id = id;
        this.name = name;
    }
    public Informationaccount(String id, Account account, String name, Integer sex, String address) {
       this.id = id;
       this.account = account;
       this.name = name;
       this.sex = sex;
       this.address = address;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


