package POJO;
// Generated Apr 10, 2017 8:42:19 PM by Hibernate Tools 4.3.1



/**
 * StudentofsubjectId generated by hbm2java
 */
public class StudentofsubjectId  implements java.io.Serializable {


     private String idsub;
     private String userName;

    public StudentofsubjectId() {
    }

    public StudentofsubjectId(String idsub, String userName) {
       this.idsub = idsub;
       this.userName = userName;
    }
   
    public String getIdsub() {
        return this.idsub;
    }
    
    public void setIdsub(String idsub) {
        this.idsub = idsub;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentofsubjectId) ) return false;
		 StudentofsubjectId castOther = ( StudentofsubjectId ) other; 
         
		 return ( (this.getIdsub()==castOther.getIdsub()) || ( this.getIdsub()!=null && castOther.getIdsub()!=null && this.getIdsub().equals(castOther.getIdsub()) ) )
 && ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdsub() == null ? 0 : this.getIdsub().hashCode() );
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         return result;
   }   


}


