package POJO;
// Generated Apr 10, 2017 8:42:19 PM by Hibernate Tools 4.3.1



/**
 * Studentofsubject generated by hbm2java
 */
public class Studentofsubject  implements java.io.Serializable {


     private StudentofsubjectId id;
     private Account account;
     private Subject subject;
     private Integer idtuan1;
     private Integer idtuan2;
     private Integer idtuan3;
     private Integer idtuan4;
     private Integer idtuan5;
     private Integer idtuan6;
     private Integer idtuan7;
     private Integer idtuan8;
     private Integer idtuan9;
     private Integer idtuan10;
     private Integer idtuan11;
     private Integer idtuan12;
     private Integer idtuan13;
     private Integer idtuan14;
     private Integer idtuan15;

    public Studentofsubject() {
    }

	
    public Studentofsubject(StudentofsubjectId id, Account account, Subject subject) {
        this.id = id;
        this.account = account;
        this.subject = subject;
    }
    public Studentofsubject(StudentofsubjectId id, Account account,
            Subject subject, Integer idtuan1, Integer idtuan2, 
            Integer idtuan3, Integer idtuan4, Integer idtuan5,
            Integer idtuan6, Integer idtuan7, Integer idtuan8, 
            Integer idtuan9, Integer idtuan10, Integer idtuan11,
            Integer idtuan12, Integer idtuan13, Integer idtuan14,
            Integer idtuan15) {
       this.id = id;
       this.account = account;
       this.subject = subject;
       this.idtuan1 = idtuan1;
       this.idtuan2 = idtuan2;
       this.idtuan3 = idtuan3;
       this.idtuan4 = idtuan4;
       this.idtuan5 = idtuan5;
       this.idtuan6 = idtuan6;
       this.idtuan7 = idtuan7;
       this.idtuan8 = idtuan8;
       this.idtuan9 = idtuan9;
       this.idtuan10 = idtuan10;
       this.idtuan11 = idtuan11;
       this.idtuan12 = idtuan12;
       this.idtuan13 = idtuan13;
       this.idtuan14 = idtuan14;
       this.idtuan15 = idtuan15;
    }
   
    public StudentofsubjectId getId() {
        return this.id;
    }
    
    public void setId(StudentofsubjectId id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public Integer getIdtuan1() {
        return this.idtuan1;
    }
    
    public void setIdtuan1(Integer idtuan1) {
        this.idtuan1 = idtuan1;
    }
    public Integer getIdtuan2() {
        return this.idtuan2;
    }
    
    public void setIdtuan2(Integer idtuan2) {
        this.idtuan2 = idtuan2;
    }
    public Integer getIdtuan3() {
        return this.idtuan3;
    }
    
    public void setIdtuan3(Integer idtuan3) {
        this.idtuan3 = idtuan3;
    }
    public Integer getIdtuan4() {
        return this.idtuan4;
    }
    
    public void setIdtuan4(Integer idtuan4) {
        this.idtuan4 = idtuan4;
    }
    public Integer getIdtuan5() {
        return this.idtuan5;
    }
    
    public void setIdtuan5(Integer idtuan5) {
        this.idtuan5 = idtuan5;
    }
    public Integer getIdtuan6() {
        return this.idtuan6;
    }
    
    public void setIdtuan6(Integer idtuan6) {
        this.idtuan6 = idtuan6;
    }
    public Integer getIdtuan7() {
        return this.idtuan7;
    }
    
    public void setIdtuan7(Integer idtuan7) {
        this.idtuan7 = idtuan7;
    }
    public Integer getIdtuan8() {
        return this.idtuan8;
    }
    
    public void setIdtuan8(Integer idtuan8) {
        this.idtuan8 = idtuan8;
    }
    public Integer getIdtuan9() {
        return this.idtuan9;
    }
    
    public void setIdtuan9(Integer idtuan9) {
        this.idtuan9 = idtuan9;
    }
    public Integer getIdtuan10() {
        return this.idtuan10;
    }
    
    public void setIdtuan10(Integer idtuan10) {
        this.idtuan10 = idtuan10;
    }
    public Integer getIdtuan11() {
        return this.idtuan11;
    }
    
    public void setIdtuan11(Integer idtuan11) {
        this.idtuan11 = idtuan11;
    }
    public Integer getIdtuan12() {
        return this.idtuan12;
    }
    
    public void setIdtuan12(Integer idtuan12) {
        this.idtuan12 = idtuan12;
    }
    public Integer getIdtuan13() {
        return this.idtuan13;
    }
    
    public void setIdtuan13(Integer idtuan13) {
        this.idtuan13 = idtuan13;
    }
    public Integer getIdtuan14() {
        return this.idtuan14;
    }
    
    public void setIdtuan14(Integer idtuan14) {
        this.idtuan14 = idtuan14;
    }
    public Integer getIdtuan15() {
        return this.idtuan15;
    }
    
    public void setIdtuan15(Integer idtuan15) {
        this.idtuan15 = idtuan15;
    }




}


