package POJO;
// Generated Apr 10, 2017 8:42:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Timetableofsubject generated by hbm2java
 */
public class Timetableofsubject  implements java.io.Serializable {


     private String idtimeDate;
     private Subject subject;
     private Date dayStart;
     private Date dayEnd;
     private Integer numberWeek;
     private String weekDays;
     private String hourStart;
     private String hourEnd;
     private String nameRoom;

    public Timetableofsubject() {
    }

	
    public Timetableofsubject(String idtimeDate) {
        this.idtimeDate = idtimeDate;
    }
    public Timetableofsubject(String idtimeDate, Subject subject, Date dayStart, Date dayEnd, Integer numberWeek, String weekDays, String hourStart, String hourEnd, String nameRoom) {
       this.idtimeDate = idtimeDate;
       this.subject = subject;
       this.dayStart = dayStart;
       this.dayEnd = dayEnd;
       this.numberWeek = numberWeek;
       this.weekDays = weekDays;
       this.hourStart = hourStart;
       this.hourEnd = hourEnd;
       this.nameRoom = nameRoom;
    }
   
    public String getIdtimeDate() {
        return this.idtimeDate;
    }
    
    public void setIdtimeDate(String idtimeDate) {
        this.idtimeDate = idtimeDate;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public Date getDayStart() {
        return this.dayStart;
    }
    
    public void setDayStart(Date dayStart) {
        this.dayStart = dayStart;
    }
    public Date getDayEnd() {
        return this.dayEnd;
    }
    
    public void setDayEnd(Date dayEnd) {
        this.dayEnd = dayEnd;
    }
    public Integer getNumberWeek() {
        return this.numberWeek;
    }
    
    public void setNumberWeek(Integer numberWeek) {
        this.numberWeek = numberWeek;
    }
    public String getWeekDays() {
        return this.weekDays;
    }
    
    public void setWeekDays(String weekDays) {
        this.weekDays = weekDays;
    }
    public String getHourStart() {
        return this.hourStart;
    }
    
    public void setHourStart(String hourStart) {
        this.hourStart = hourStart;
    }
    public String getHourEnd() {
        return this.hourEnd;
    }
    
    public void setHourEnd(String hourEnd) {
        this.hourEnd = hourEnd;
    }
    public String getNameRoom() {
        return this.nameRoom;
    }
    
    public void setNameRoom(String nameRoom) {
        this.nameRoom = nameRoom;
    }




}


