-- MySQL Script generated by MySQL Workbench
-- 04/15/17 19:15:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quanlysvmh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quanlysvmh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlysvmh` DEFAULT CHARACTER SET utf8 ;
USE `quanlysvmh` ;

-- -----------------------------------------------------
-- Table `quanlysvmh`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysvmh`.`account` (
  `UserName` VARCHAR(50) NOT NULL,
  `PassWord` VARCHAR(50) NOT NULL,
  `Type` INT(11) NOT NULL,
  PRIMARY KEY (`UserName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlysvmh`.`informationaccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysvmh`.`informationaccount` (
  `ID` VARCHAR(7) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Sex` INT(11) NULL DEFAULT NULL,
  `Address` VARCHAR(50) NULL DEFAULT NULL,
  `UserName` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `UserName` (`UserName` ASC),
  CONSTRAINT `informationaccount_ibfk_1`
    FOREIGN KEY (`UserName`)
    REFERENCES `quanlysvmh`.`account` (`UserName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlysvmh`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysvmh`.`subject` (
  `ID` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Creator` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Creator` (`Creator` ASC),
  CONSTRAINT `subject_ibfk_1`
    FOREIGN KEY (`Creator`)
    REFERENCES `quanlysvmh`.`account` (`UserName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlysvmh`.`studentofsubject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysvmh`.`studentofsubject` (
  `IDSub` VARCHAR(10) NOT NULL,
  `UserName` VARCHAR(50) NOT NULL,
  `IDTuan1` INT(11) NULL DEFAULT NULL,
  `IDTuan2` INT(11) NULL DEFAULT NULL,
  `IDTuan3` INT(11) NULL DEFAULT NULL,
  `IDTuan4` INT(11) NULL DEFAULT NULL,
  `IDTuan5` INT(11) NULL DEFAULT NULL,
  `IDTuan6` INT(11) NULL DEFAULT NULL,
  `IDTuan7` INT(11) NULL DEFAULT NULL,
  `IDTuan8` INT(11) NULL DEFAULT NULL,
  `IDTuan9` INT(11) NULL DEFAULT NULL,
  `IDTuan10` INT(11) NULL DEFAULT NULL,
  `IDTuan11` INT(11) NULL DEFAULT NULL,
  `IDTuan12` INT(11) NULL DEFAULT NULL,
  `IDTuan13` INT(11) NULL DEFAULT NULL,
  `IDTuan14` INT(11) NULL DEFAULT NULL,
  `IDTuan15` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IDSub`, `UserName`),
  INDEX `UserName` (`UserName` ASC),
  CONSTRAINT `studentofsubject_ibfk_1`
    FOREIGN KEY (`IDSub`)
    REFERENCES `quanlysvmh`.`subject` (`ID`),
  CONSTRAINT `studentofsubject_ibfk_2`
    FOREIGN KEY (`UserName`)
    REFERENCES `quanlysvmh`.`account` (`UserName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlysvmh`.`timetableofsubject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysvmh`.`timetableofsubject` (
  `IDTimeDate` VARCHAR(50) NOT NULL,
  `IDSub` VARCHAR(10) NULL DEFAULT NULL,
  `DayStart` DATE NULL DEFAULT NULL,
  `DayEnd` DATE NULL DEFAULT NULL,
  `NumberWeek` INT(11) NULL DEFAULT NULL,
  `WeekDays` VARCHAR(10) NULL DEFAULT NULL,
  `HourStart` VARCHAR(10) NULL DEFAULT NULL,
  `HourEnd` VARCHAR(10) NULL DEFAULT NULL,
  `NameRoom` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`IDTimeDate`),
  INDEX `IDSub` (`IDSub` ASC),
  CONSTRAINT `timetableofsubject_ibfk_1`
    FOREIGN KEY (`IDSub`)
    REFERENCES `quanlysvmh`.`subject` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
